### ISSUE TITLE
How do i Fix this Error 

### ISSUE THREAD

**Issue by ezrasoft** [Sledro/PHP-Login#1]
Parse error: syntax error, unexpected end of file in C:\xampp\htdocs\fyambe.news\login\forgotPassword.php on line 120

**Comment by sledro** [comment]
Sorry for the late reply. Not sure why you are getting this error. The code works fine for me. Let me know if you are still having issues.

**Comment by adesignguy** [comment]
Hi,

 

To be honest it’s been so long I can’t remember if I fixed it or not, I’m thinking the reason was I’m using the latest version of PHP.

 

Thanks,

Chris.
